### PR TITLE
Basic Feature of the App.

### PR DESCRIPTION
**Pull request by D-sense**
I created the basic feature of the app: registration, login, migrations, models, and relationships.

### CODE REVIEW

**Comment by D-sense** [comment]
Any update on this?
I noticed you merged a PR earlier which created the framework in a subfolder of the root folder .

**Comment by KingAviator** [comment]
Frontend team are working on the same repo
Just to seperate server from client

**Comment by D-sense** [comment]
Ok, I got it. That was made known earlier. What is the way out?

**Comment by KingAviator** [comment]
I have told the frotend team to do same by creating a subfolder named client where the can pull from and start work

**Comment by KingAviator** [comment]
The were just sending PR with no base structure

**Comment by D-sense** [comment]
Cool, I get it. Alright, I will see make changes on my end and send a new PR.

**Comment by KingAviator** [comment]
Alright boss
Just to be clear, The user reg details you created, did you use make:auth or it was done by you

**Comment by D-sense** [comment]
It was done by me to allow for quick modification and to enable Laravel newbie to understand the registration process better and contribute effectively.

**Comment by Jolaolu** [comment]
> Alright boss
> Just to be clear, The user reg details you created, did you use make:auth or it was done by you

is there any reason you ask?

so I don't make the same mistake

**Pull request closed without merging**
