### PR TITLE
Social app edited i created the tables we need and a basic registration using auth

### PR DESCRIPTION
**Pull request by RaphAlemoh**
…on system

### CODE REVIEW

**Comment by RaphAlemoh** [comment]
who has the front end code lets make this work

**Comment by KingAviator** [comment]
Hello thanks for your work
Please be part of the team on slack to discuss this intergration futher

#Thats where work happens

**Comment by RaphAlemoh** [comment]
oryt i will join you soon

**Comment by thecodearcher** [comment]
Fix merge conflict.

**Pull request closed without merging**
