### PR TITLE
Models and folders

### PR DESCRIPTION
**Pull request by Jolaolu**
I Created admin, includes, layout, pages, and posts folders to make File Directory structure clean and not cluttered, I also created Posts and Comments model with their controllers and migrations

### CODE REVIEW

**Comment by RaphAlemoh** [comment]
good

**Comment by KingAviator** [comment]
Great work

**Comment by thecodearcher** [comment]
Nice work so far but we need to add the needed fields also before creating the migrations to prevent multiple additional migration files.

**Comment by Jolaolu** [comment]
> Nice work so far but we need to add the needed fields also before creating the migrations to prevent multiple additional migration files.

but any other person can do a migration:refresh or migration:fresh, I didn't edit anything in the pre-created migration table .
jut the expanded the base of the project to give it a  better structure
thing would just move on from there

**Pull request closed without merging**
