### PR TITLE
completed user registration, login, created friends and posts migrati…

### PR DESCRIPTION
**Pull request by D-sense**
completed user registration, login, created friends and posts migrati…

### CODE REVIEW

**Comment by D-sense** [comment]
Hi boss...kindly review. Thanks!

**Comment by thecodearcher** [comment]
Please add  /.idea to your git ignore

**Comment by D-sense** [comment]
Done.

**Comment by thecodearcher** [comment]
Your .idea files are still being pushed. Did you make any edit to the base .gitignore? also if you want to ignore any file add it to the base .gitignore, so I will close this PR so you can rectify the gitignore issue when u are done create a PR again ensuring only the needed code is committed. :smiley:

**Pull request closed without merging**
